# Generated by Django 5.0.6 on 2024-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
