# Generated by Django 5.0.6 on 2024-05-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0004_message_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
