# Generated by Django 5.0.6 on 2024-05-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0009_message_guess_lu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='lien',
        ),
        migrations.AddField(
            model_name='projet',
            name='domaine',
            field=models.CharField(default='Développement web', max_length=200),
        ),
    ]
