# Generated by Django 5.0.6 on 2024-05-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rendu', '0010_remove_projet_date_debut_remove_projet_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(upload_to='images/tech/')),
            ],
        ),
    ]
